# Generated by Django 3.0.8 on 2020-07-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200716_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempts',
            name='login_status',
            field=models.CharField(choices=[('failed', 'failed'), ('success', 'success')], max_length=7),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='result',
            field=models.CharField(choices=[('correct', 'correct'), ('incorrect', 'incorrect')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userrelationships',
            name='relationship_status',
            field=models.CharField(choices=[('pending', 'pending'), ('friends', 'friends'), ('blocked', 'blocked')], max_length=7),
        ),
    ]
