# Generated by Django 3.0.8 on 2020-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0004_auto_20200716_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='time_taken_seeconds',
            new_name='time_taken_seconds',
        ),
        migrations.AlterField(
            model_name='practice',
            name='score',
            field=models.SmallIntegerField(),
        ),
    ]
