# Generated by Django 3.0.8 on 2020-07-16 19:34

import Database.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_auto_20200716_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='fifth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(Database.models.get_sentinel_user), related_name='fifth_place_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='results',
            name='fourth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(Database.models.get_sentinel_user), related_name='fourth_place_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='results',
            name='sixth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(Database.models.get_sentinel_user), related_name='sixth_place_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='results',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(Database.models.get_sentinel_user), related_name='third_place_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
