# Generated by Django 3.0.8 on 2020-07-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_auto_20200716_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='result',
            new_name='winner',
        ),
    ]
