# Generated by Django 3.0.8 on 2020-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0008_auto_20200716_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscores',
            name='game',
        ),
        migrations.AlterField(
            model_name='practice',
            name='time_taken_seconds',
            field=models.CharField(max_length=10),
        ),
    ]
