# Generated by Django 3.0.8 on 2020-07-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_auto_20200716_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscores',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='userscores',
            name='time_taken_seconds',
            field=models.CharField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
