# Generated by Django 3.0.8 on 2020-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0010_auto_20200716_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
